### PR TITLE
Prepare first PyPi release

### PR DESCRIPTION
**Pull request by lrq3000**
Prepare for first release:
* Add badges in README
* Add me as a maintainer in pyproject.toml, to ensure PyPi automatic security system accepts me pushing the package
* Check/tweak continuous deployment and secrets
* More?...

~~Not~~ ready to be merged!

### CODE REVIEW

**Comment by eobrain** [comment]
Hey Stephen, following up the discussion in #1 ...

I don't think it is worth it to  make this project into a GitHub organization, so if you could send me instructions for setting the secrets, that would be great.

You can email me at  `eobrain` AT `proton.me`

Or DM me at `@eob` on Twitter or at `@eob@social.coop` on Mastodon.

Thanks

**Comment by lrq3000** [comment]
Ok awesome, I sent you an e-mail with the secrets to add and the instructions, thank you very much! :D

**Comment by lrq3000** [comment]
@eobrain This PR is ready! I already published a release from this branch, so I know it works.

I also added a logo I made, I'm not a graphist, so if you don't like it don't worry I won't take it badly :-) Let me know if you want to keep it or not:

https://github.com/eobrain/videogestalt/blob/prepare-first-release/resources/videogestalt_logo.png

**Comment by eobrain** [comment]
The logo is great!

**Review by eobrain — APPROVED** [review]

**Review by eobrain — APPROVED** [review]

**Review by eobrain — APPROVED** [review]

**Comment by lrq3000** [comment]
Thank you very much @eobrain ! :D

Sorry you had some difficulties to merge, it was because one unit test failed and it was not because of us but GitHub Actions sometimes failing to setup the test environment 😅 We can just re-run the failed unit-tests in these cases :-)

Everything is in order now, I'm merging, thank you very much for your help all along and your trust!

For the moment I don't think I have anything else to add, but maybe in the future I will try to optimize a bit the performance if I can find a way, notably by parallelization, we'll see in another PR if I can make it work :-)

**Pull request merged**
